apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret-{{ .Release.Namespace }}
type: Opaque
data:
  rootPassword: cGFzc3dvcmQ= # password
  user: YWlybGluZXM=  # airlines
  password: cGFzc3dvcmQ= # password
